{-# LANGUAGE FlexibleInstances, OverlappingInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGCL.
--   Generated by the BNF converter.

module PrintGCL where

import AbsGCL
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Ident where
  prt _ (Ident i) = doc (showString i)

instance Print Stm where
  prt i e = case e of
    Stm_skip -> prPrec i 0 (concatD [doc (showString "skip")])
    StmA a -> prPrec i 0 (concatD [prt 0 a])
    Stm1 guard -> prPrec i 0 (concatD [doc (showString "if"), prt 0 guard, doc (showString "fi")])
    Stm2 guard -> prPrec i 0 (concatD [doc (showString "do"), prt 0 guard, doc (showString "od")])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [Stm] where
  prt = prtList

instance Print A where
  prt i e = case e of
    A1 id intexpv -> prPrec i 0 (concatD [prt 0 id, doc (showString ":="), prt 0 intexpv])
    A2 id a intexpv -> prPrec i 0 (concatD [prt 0 id, doc (showString ","), prt 0 a, doc (showString ","), prt 0 intexpv])

instance Print Guard where
  prt i e = case e of
    Ass pred stm -> prPrec i 0 (concatD [prt 0 pred, doc (showString "->"), prt 0 stm])
    Comp guard1 guard2 -> prPrec i 0 (concatD [prt 0 guard1, doc (showString "[]"), prt 0 guard2])

instance Print Pred where
  prt i e = case e of
    F -> prPrec i 0 (concatD [doc (showString "FALSE")])
    Imp pred1 pred2 -> prPrec i 0 (concatD [prt 0 pred1, doc (showString "=>"), prt 0 pred2])
    Rel relation -> prPrec i 0 (concatD [prt 0 relation])

instance Print Relation where
  prt i e = case e of
    Eq intexpv1 intexpv2 -> prPrec i 0 (concatD [prt 0 intexpv1, doc (showString "="), prt 0 intexpv2])
    Lt intexpv1 intexpv2 -> prPrec i 0 (concatD [prt 0 intexpv1, doc (showString "<"), prt 0 intexpv2])

instance Print Id where
  prt i e = case e of
    Lst id -> prPrec i 0 (concatD [prt 0 id])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Id] where
  prt = prtList

instance Print Exp where
  prt i e = case e of
    Els intexpv -> prPrec i 0 (concatD [prt 0 intexpv])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Exp] where
  prt = prtList

instance Print IntExpV where
  prt i e = case e of
    Add intexpv1 intexpv2 -> prPrec i 0 (concatD [prt 1 intexpv1, doc (showString "+"), prt 0 intexpv2])
    Mul intexpv1 intexpv2 -> prPrec i 1 (concatD [prt 2 intexpv1, doc (showString "*"), prt 1 intexpv2])
    Neg intexpv -> prPrec i 2 (concatD [doc (showString "NEG"), prt 2 intexpv])
    Nmb n -> prPrec i 3 (concatD [prt 0 n])
    Var id -> prPrec i 3 (concatD [prt 0 id])

