module SkelElement where

-- Haskell module generated by the BNF converter

import AbsElement
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transCIdent :: CIdent -> Result
transCIdent x = case x of
  CIdent string -> failure x
transTeX :: TeX -> Result
transTeX x = case x of
  TeX string -> failure x
transWeird :: Weird -> Result
transWeird x = case x of
  Weird string -> failure x
transSubscript :: Subscript -> Result
transSubscript x = case x of
  Subscript string -> failure x
transElement :: Element -> Result
transElement x = case x of
  Cid cident -> failure x
  Tex tex -> failure x
  Wrd weird -> failure x
  Sub subscript -> failure x

