module SkelIntExpV where

-- Haskell module generated by the BNF converter

import AbsIntExpV
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transIntExp :: IntExp -> Result
transIntExp x = case x of
  Add intexp1 intexp2 -> failure x
  Mul intexp1 intexp2 -> failure x
  Neg intexp -> failure x
  Nmb integer -> failure x
  Var ident -> failure x

