{-# LANGUAGE FlexibleInstances, OverlappingInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintN.
--   Generated by the BNF converter.

module PrintN where

import AbsN
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Ident where
  prt _ (Ident i) = doc (showString i)
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print V where
  prt i e = case e of
    Var id t -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), prt 0 t])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print T where
  prt i e = case e of
    Int -> prPrec i 0 (concatD [doc (showString "Int")])
    Bool -> prPrec i 0 (concatD [doc (showString "Bool")])

instance Print P where
  prt i e = case e of
    Proc id vs1 vs2 s -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), doc (showString "{"), prt 0 vs1, doc (showString "|"), prt 0 vs2, doc (showString "|"), prt 0 s, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [P] where
  prt = prtList

instance Print [V] where
  prt = prtList

instance Print D where
  prt i e = case e of
    Dvar v -> prPrec i 0 (concatD [prt 0 v])
    Dpr p -> prPrec i 0 (concatD [prt 0 p])

instance Print S where
  prt i e = case e of
    Skp -> prPrec i 0 (concatD [doc (showString "skip")])
    Prn e_ -> prPrec i 0 (concatD [doc (showString "print"), prt 0 e_])
    Ass id e_ -> prPrec i 0 (concatD [prt 0 id, doc (showString ":="), prt 0 e_])
    Cho e_ s1 s2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 e_, doc (showString "then"), prt 0 s1, doc (showString "else"), prt 0 s2, doc (showString "end")])
    Itr e_ s -> prPrec i 0 (concatD [doc (showString "while"), prt 0 e_, doc (showString "do"), prt 0 s, doc (showString "end")])
    Dcl d s -> prPrec i 0 (concatD [doc (showString "{"), prt 0 d, doc (showString ";"), prt 0 s, doc (showString "}")])
    Call id es ids -> prPrec i 0 (concatD [prt 0 id, doc (showString "{"), prt 0 es, doc (showString "|"), prt 0 ids, doc (showString "}")])
    Seq ss -> prPrec i 0 (concatD [prt 0 ss])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [Ident] where
  prt = prtList

instance Print [E] where
  prt = prtList

instance Print [S] where
  prt = prtList

instance Print E where
  prt i e = case e of
    Lt e_1 e_2 -> prPrec i 0 (concatD [prt 1 e_1, doc (showString "<"), prt 0 e_2])
    Eq e_1 e_2 -> prPrec i 1 (concatD [prt 2 e_1, doc (showString "="), prt 1 e_2])
    And e_1 e_2 -> prPrec i 2 (concatD [prt 3 e_1, doc (showString "and"), prt 2 e_2])
    Or e_1 e_2 -> prPrec i 3 (concatD [prt 4 e_1, doc (showString "or"), prt 3 e_2])
    Not e_ -> prPrec i 4 (concatD [doc (showString "not"), prt 4 e_])
    Fls -> prPrec i 5 (concatD [doc (showString "false")])
    Tr -> prPrec i 5 (concatD [doc (showString "true")])
    Sum e_1 e_2 -> prPrec i 6 (concatD [prt 7 e_1, doc (showString "+"), prt 6 e_2])
    Mul e_1 e_2 -> prPrec i 7 (concatD [prt 8 e_1, doc (showString "*"), prt 7 e_2])
    Neg e_ -> prPrec i 8 (concatD [doc (showString "neg"), prt 8 e_])
    Iex n -> prPrec i 9 (concatD [prt 0 n])
    Idex id -> prPrec i 9 (concatD [prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

